server:
  port: 8080
spring:
  application:
    name: car-rental-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: users-service
              uri: ${USERS_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/user/**
              filters:
                - AddResponseHeader=X-Powered-By,Spring Cloud Gateway
            - id: cars-service
              uri: ${CARS_SERVICE_URL:http://localhost:8084}
              predicates:
                - Path=/api/cars/**
              filters:
                - AddResponseHeader=X-Powered-By,Spring Cloud Gateway
            - id: resources-service
              uri: ${RESOURCES_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/api/resources/**
              filters:
                - AddResponseHeader=X-Powered-By,Spring Cloud Gateway

# Desactivar Eureka
eureka:
  client:
    enabled: false

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route: DEBUG
    org.springframework.cloud.gateway.handler: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    reactor.netty: DEBUG
